"""ThreeQueueScheduler — the core execution loop for the MDF simulation engine.

Implements the priority/standard/delay queue model from the simulation engine
design doc (rules 1-11, 18-25). Run-to-completion semantics: events generated
during action execution are buffered and flushed only after the current event's
transition fully completes.

Queue routing rules (D-10..D-15):
    - Priority queue: self-directed events (sender == target)
    - Standard queue: cross-instance, creation, deletion, and expired delayed
    - Delay queue: events with delay_ms > 0, min-heap on (expiry, seq)

The scheduler is intentionally schema/-tools/-pycca/-free per D-37; it consumes
a `dict[str, ClassManifest]` produced upstream by the compiler.
"""
from __future__ import annotations

import heapq
from collections import deque
from typing import Any, Generator

from engine.clock import SimulationClock
from engine.event import Event, make_instance_key
from engine.manifest import ClassManifest
from engine.microstep import (
    ActionExecuted,
    ErrorMicroStep,
    EventCancelled,
    EventDelayed,
    EventDelayExpired,
    EventReceived,
    GenerateDispatched,
    GuardEvaluated,
    InstanceDeleted,
    MicroStep,
    SchedulerSelected,
    TransitionFired,
)
from engine.registry import InstanceRegistry


def _id_key(class_name: str, identifier: dict) -> tuple[str, frozenset]:
    return (class_name, make_instance_key(identifier))


class ThreeQueueScheduler:
    """Three-queue event scheduler with run-to-completion semantics."""

    def __init__(
        self,
        registry: InstanceRegistry,
        clock: SimulationClock,
        class_defs: dict[str, ClassManifest],
        generalizations: dict[str, list[str]] | None = None,
        ctx: Any = None,
    ):
        self._registry = registry
        self._clock = clock
        self._class_defs = class_defs
        self._generalizations = generalizations or {}
        # SimulationContext back-reference; set after construction so generated
        # action functions can call ctx.generate() / ctx.bridge() (D-35 / D-36).
        self._ctx: Any = ctx

        self._priority: deque[Event] = deque()
        self._standard: deque[Event] = deque()
        # Min-heap entries: (expiry_ms, seq, event)
        self._delay: list[tuple[float, int, Event]] = []
        self._seq: int = 0

        # Run-to-completion buffer: events generated by an action_fn while an
        # event is in flight. Flushed after the current event completes.
        self._pending_generated: list[Event] = []
        self._in_flight: Event | None = None

    # ------------------------------------------------------------------
    # Enqueue / cancel / delay tick
    # ------------------------------------------------------------------

    def enqueue(self, event: Event) -> list[MicroStep]:
        """Route an event to the correct queue per D-10..D-14.

        If the scheduler is currently processing an event (run-to-completion),
        the event is buffered in _pending_generated and dispatched only after
        the current event completes (D-18, D-19).
        """
        # Delay queue takes precedence over self/cross routing (rule 5)
        if event.delay_ms is not None and event.delay_ms > 0:
            return self._enqueue_delay(event)

        # Run-to-completion buffer
        if self._in_flight is not None:
            self._pending_generated.append(event)
            queue = self._classify_queue(event)
            return [
                GenerateDispatched(
                    event_type=event.event_type,
                    sending_class=event.sender_class,
                    sending_instance_id=dict(event.sender_id),
                    target_class=event.target_class,
                    target_instance_id=dict(event.target_id),
                    args=dict(event.args),
                    queue=queue,
                )
            ]

        return self._enqueue_direct(event)

    def _classify_queue(self, event: Event) -> str:
        """Return 'priority' or 'standard' for an immediate event."""
        # Creation/deletion are always standard (rule 3)
        if event.event_type in ("__creation__", "__deletion__"):
            return "standard"
        # Self-directed -> priority (rule 1)
        if (
            event.sender_class == event.target_class
            and event.sender_id == event.target_id
        ):
            return "priority"
        return "standard"

    def _enqueue_direct(self, event: Event) -> list[MicroStep]:
        queue = self._classify_queue(event)
        if queue == "priority":
            self._priority.append(event)
        else:
            self._standard.append(event)
        return [
            GenerateDispatched(
                event_type=event.event_type,
                sending_class=event.sender_class,
                sending_instance_id=dict(event.sender_id),
                target_class=event.target_class,
                target_instance_id=dict(event.target_id),
                args=dict(event.args),
                queue=queue,
            )
        ]

    def _enqueue_delay(self, event: Event) -> list[MicroStep]:
        """Enqueue a delayed event with at-most-one-per-triple invariant (D-14)."""
        # Remove any existing delayed event with the same (type, sender, target)
        sender_key = make_instance_key(event.sender_id)
        target_key = make_instance_key(event.target_id)
        keep: list[tuple[float, int, Event]] = []
        for entry in self._delay:
            _, _, e = entry
            if (
                e.event_type == event.event_type
                and e.sender_class == event.sender_class
                and make_instance_key(e.sender_id) == sender_key
                and e.target_class == event.target_class
                and make_instance_key(e.target_id) == target_key
            ):
                continue  # drop the existing one
            keep.append(entry)
        if len(keep) != len(self._delay):
            self._delay = keep
            heapq.heapify(self._delay)

        expiry = self._clock.now() + (event.delay_ms or 0.0)
        heapq.heappush(self._delay, (expiry, self._seq, event))
        self._seq += 1
        return [
            EventDelayed(
                event_type=event.event_type,
                sending_class=event.sender_class,
                sending_instance_id=dict(event.sender_id),
                target_class=event.target_class,
                target_instance_id=dict(event.target_id),
                args=dict(event.args),
                delay_ms=float(event.delay_ms or 0.0),
            )
        ]

    def cancel(
        self, event_type: str, sender_class: str, sender_id: dict,
        target_class: str, target_id: dict,
    ) -> list[MicroStep]:
        """Remove a matching delayed event from the delay queue (D-25)."""
        sender_key = make_instance_key(sender_id)
        target_key = make_instance_key(target_id)
        keep: list[tuple[float, int, Event]] = []
        cancelled = False
        for entry in self._delay:
            _, _, e = entry
            if (
                not cancelled
                and e.event_type == event_type
                and e.sender_class == sender_class
                and make_instance_key(e.sender_id) == sender_key
                and e.target_class == target_class
                and make_instance_key(e.target_id) == target_key
            ):
                cancelled = True
                continue
            keep.append(entry)
        if cancelled:
            self._delay = keep
            heapq.heapify(self._delay)
            return [
                EventCancelled(
                    cancelled_event_type=event_type,
                    sender_id=dict(sender_id),
                    target_id=dict(target_id),
                )
            ]
        return []

    @staticmethod
    def _is_generated_action(fn) -> bool:
        """Return True if fn uses the generated-code (ctx, self_dict, params) signature.

        Generated modules name their first parameter 'ctx'. Test helpers typically
        use 'instance' or '*_a'. We use inspect to check without importing schema/.
        """
        import inspect
        try:
            sig = inspect.signature(fn)
            params = list(sig.parameters)
            return bool(params) and params[0] == "ctx"
        except (ValueError, TypeError):
            return False

    def _invoke_action(self, action_fn, instance: dict, args: dict):
        """Call an action function with the appropriate signature.

        Generated code uses (ctx, self_dict, params) where ctx is the
        SimulationContext. Legacy test actions use (instance, args, scheduler)
        or (instance, args). This method dispatches based on the first
        parameter name:

          - First param 'ctx'  → generated-code shape: (ctx, instance, args)
          - Otherwise          → legacy shape: (instance, args, self) or (instance, args)
        """
        if self._ctx is not None and self._is_generated_action(action_fn):
            return action_fn(self._ctx, instance, args)
        try:
            return action_fn(instance, args, self)
        except TypeError:
            return action_fn(instance, args)

    def tick_delay_queue(self) -> list[MicroStep]:
        """Move expired delayed events to the standard queue (rule 8)."""
        steps: list[MicroStep] = []
        now = self._clock.now()
        while self._delay and self._delay[0][0] <= now:
            _, _, event = heapq.heappop(self._delay)
            # Strip delay_ms and re-route using normal priority/standard rules
            unwrapped = Event(
                event_type=event.event_type,
                sender_class=event.sender_class,
                sender_id=dict(event.sender_id),
                target_class=event.target_class,
                target_id=dict(event.target_id),
                args=dict(event.args),
                delay_ms=None,
            )
            queue = self._classify_queue(unwrapped)
            if queue == "priority":
                self._priority.append(unwrapped)
            else:
                self._standard.append(unwrapped)
            steps.append(
                EventDelayExpired(
                    event_type=event.event_type,
                    target_class=event.target_class,
                    target_instance_id=dict(event.target_id),
                )
            )
        return steps

    # ------------------------------------------------------------------
    # Polymorphic dispatch helper
    # ------------------------------------------------------------------

    def _resolve_target(
        self, target_class: str, target_id: dict
    ) -> tuple[str | None, dict | None]:
        """Resolve a (possibly supertype) target to a concrete instance.

        Returns (concrete_class, concrete_id) or (None, None) if no instance
        exists. Per D-20: a supertype-targeted event is routed to whichever
        subtype currently has an instance with the matching identifier.
        """
        # Direct lookup first
        if self._registry.lookup(target_class, target_id) is not None:
            return target_class, target_id

        # Try subtypes (polymorphic dispatch)
        subtypes = self._generalizations.get(target_class, [])
        for sub in subtypes:
            if self._registry.lookup(sub, target_id) is not None:
                return sub, target_id

        return None, None

    # ------------------------------------------------------------------
    # Main execute loop
    # ------------------------------------------------------------------

    def execute(self) -> Generator[MicroStep, None, None]:
        """Run the scheduler until all queues are empty (rule 9 — domain idle)."""
        while True:
            # Always tick the delay queue first so expired events feed standard
            for step in self.tick_delay_queue():
                yield step

            if self._priority:
                event = self._priority.popleft()
                yield SchedulerSelected(
                    queue="priority",
                    event_type=event.event_type,
                    target_class=event.target_class,
                    target_instance_id=dict(event.target_id),
                )
                for step in self._process_event(event, queue="priority"):
                    yield step
            elif self._standard:
                event = self._standard.popleft()
                yield SchedulerSelected(
                    queue="standard",
                    event_type=event.event_type,
                    target_class=event.target_class,
                    target_instance_id=dict(event.target_id),
                )
                for step in self._process_event(event, queue="standard"):
                    yield step
            else:
                # All queues empty — domain idle (rule 9)
                break

    # ------------------------------------------------------------------
    # Per-event processing
    # ------------------------------------------------------------------

    def _process_event(
        self, event: Event, queue: str
    ) -> Generator[MicroStep, None, None]:
        # Special: creation event sets the initial state and runs entry action
        if event.event_type == "__creation__":
            yield from self._process_creation(event, queue)
            return

        # Special: deletion event triggers process_deletion
        if event.event_type == "__deletion__":
            yield from self._process_deletion(event, queue)
            return

        # Resolve target (handles polymorphic dispatch per D-20)
        concrete_class, concrete_id = self._resolve_target(
            event.target_class, event.target_id
        )
        if concrete_class is None:
            yield ErrorMicroStep(
                error_kind="unknown_target",
                message=(
                    f"No instance {event.target_class} {event.target_id} for "
                    f"event {event.event_type}"
                ),
                context={
                    "event_type": event.event_type,
                    "target_class": event.target_class,
                    "target_id": dict(event.target_id),
                },
            )
            return

        cdef = self._class_defs.get(concrete_class)
        if cdef is None:
            yield ErrorMicroStep(
                error_kind="unknown_class",
                message=f"Unknown class {concrete_class}",
                context={"class": concrete_class},
            )
            return

        curr_state = self._registry.get_state(concrete_class, concrete_id)

        yield EventReceived(
            class_name=concrete_class,
            instance_id=dict(concrete_id),
            event_type=event.event_type,
            args=dict(event.args),
            queue=queue,  # type: ignore[arg-type]
        )

        ttable = cdef.get("transition_table", {})
        entry = ttable.get((curr_state, event.event_type))

        if entry is None:
            yield ErrorMicroStep(
                error_kind="cant_happen",
                message=(
                    f"Can't happen: {concrete_class} in state {curr_state!r} "
                    f"received {event.event_type}"
                ),
                context={
                    "class": concrete_class,
                    "state": curr_state,
                    "event_type": event.event_type,
                },
            )
            return

        next_state = entry.get("next_state")
        action_fn = entry.get("action_fn")
        guard_fn = entry.get("guard_fn")

        # event-ignored: present in table with next_state=None and no fns
        if next_state is None and action_fn is None and guard_fn is None:
            return

        # Guard evaluation
        if guard_fn is not None:
            try:
                result = bool(guard_fn(
                    self._registry.lookup(concrete_class, concrete_id),
                    dict(event.args),
                ))
            except Exception as exc:
                yield ErrorMicroStep(
                    error_kind="guard_error",
                    message=str(exc),
                    context={"class": concrete_class, "event_type": event.event_type},
                )
                return
            yield GuardEvaluated(
                expression=getattr(guard_fn, "__name__", "<guard>"),
                result=result,
                variable_values={},
            )
            if not result:
                return

        # Run-to-completion: mark in-flight before invoking action
        self._in_flight = event
        try:
            assignments: dict = {}
            if action_fn is not None:
                instance = self._registry.lookup(concrete_class, concrete_id)
                ret = self._invoke_action(action_fn, instance, dict(event.args))
                if isinstance(ret, dict):
                    assignments = ret
                yield ActionExecuted(
                    pycca_line=getattr(action_fn, "__name__", "<action>"),
                    assignments_made=assignments,
                )

            from_state = curr_state
            if next_state is not None:
                self._registry.set_state(concrete_class, concrete_id, next_state)
                yield TransitionFired(
                    from_state=from_state if from_state is not None else "",
                    to_state=next_state,
                    class_name=concrete_class,
                    instance_id=dict(concrete_id),
                )

            # D-23/D-24: final state -> async deletion
            final_states = cdef.get("final_states", []) or []
            if next_state is not None and next_state in final_states:
                del_evt = self._registry.delete_async(concrete_class, concrete_id)
                if del_evt is not None:
                    # Use direct enqueue (don't buffer — we're flushing already)
                    self._pending_generated.append(del_evt)
        finally:
            # Flush run-to-completion buffer
            buffered = self._pending_generated
            self._pending_generated = []
            self._in_flight = None
            for buffered_event in buffered:
                self._enqueue_direct(buffered_event)

    def _process_creation(
        self, event: Event, queue: str
    ) -> Generator[MicroStep, None, None]:
        target_class = event.target_class
        target_id = event.target_id
        cdef = self._class_defs.get(target_class)
        if cdef is None:
            yield ErrorMicroStep(
                error_kind="unknown_class",
                message=f"Unknown class {target_class}",
                context={"class": target_class},
            )
            return

        initial_state = event.args.get("initial_state") or cdef.get("initial_state")
        if initial_state is not None:
            self._registry.set_state(target_class, target_id, initial_state)

        yield EventReceived(
            class_name=target_class,
            instance_id=dict(target_id),
            event_type="__creation__",
            args=dict(event.args),
            queue=queue,  # type: ignore[arg-type]
        )

        # Optional entry action: look up (None, "__creation__") in transition table
        ttable = cdef.get("transition_table", {})
        entry = ttable.get((None, "__creation__"))
        if entry is not None and entry.get("action_fn") is not None:
            self._in_flight = event
            try:
                action_fn = entry["action_fn"]
                instance = self._registry.lookup(target_class, target_id)
                ret = self._invoke_action(action_fn, instance, dict(event.args))
                yield ActionExecuted(
                    pycca_line=getattr(action_fn, "__name__", "<entry>"),
                    assignments_made=ret if isinstance(ret, dict) else {},
                )
            finally:
                buffered = self._pending_generated
                self._pending_generated = []
                self._in_flight = None
                for be in buffered:
                    self._enqueue_direct(be)

    def _process_deletion(
        self, event: Event, queue: str
    ) -> Generator[MicroStep, None, None]:
        target_class = event.target_class
        target_id = event.target_id
        steps = self._registry.process_deletion(target_class, target_id)
        for step in steps:
            yield step
